name: check_raspadores
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/usinas.json
    - assets/logo.png   # 👈 adiciona o logo nos assets também

# 🔹 Configuração do flutter_launcher_icons (fora de dependencies)
flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/logo.png"
