// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABTMwMnTa4d8durZYyARIJReSkv74Wck8',
    appId: '1:184980334280:web:828e39cde5cdf7c11d27fd',
    messagingSenderId: '184980334280',
    projectId: 'check-raspadores',
    authDomain: 'check-raspadores.firebaseapp.com',
    storageBucket: 'check-raspadores.firebasestorage.app',
    measurementId: 'G-TK1M3R9QEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDPqXPZj4FtgSVSdSQFyC7RYJOV6-qn2k',
    appId: '1:184980334280:android:494406534f72ef261d27fd',
    messagingSenderId: '184980334280',
    projectId: 'check-raspadores',
    storageBucket: 'check-raspadores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3UCk2SSbsDQ5PrfUB5DgM0OXTnoEsauQ',
    appId: '1:184980334280:ios:34ea32f0c85103581d27fd',
    messagingSenderId: '184980334280',
    projectId: 'check-raspadores',
    storageBucket: 'check-raspadores.firebasestorage.app',
    iosBundleId: 'com.fns.checkRaspadores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3UCk2SSbsDQ5PrfUB5DgM0OXTnoEsauQ',
    appId: '1:184980334280:ios:34ea32f0c85103581d27fd',
    messagingSenderId: '184980334280',
    projectId: 'check-raspadores',
    storageBucket: 'check-raspadores.firebasestorage.app',
    iosBundleId: 'com.fns.checkRaspadores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABTMwMnTa4d8durZYyARIJReSkv74Wck8',
    appId: '1:184980334280:web:842484fd45fe386a1d27fd',
    messagingSenderId: '184980334280',
    projectId: 'check-raspadores',
    authDomain: 'check-raspadores.firebaseapp.com',
    storageBucket: 'check-raspadores.firebasestorage.app',
    measurementId: 'G-9Z4B8YV27N',
  );
}
